dockerfile and startApp.sh files fixed to work on mac and windows
ibm-messaging/mq-dev-badge-sample pull request #25
Opened 2024-08-05 09:18 UTC by shreeya1510

changes in both files to work on both architectures - arm64 & amd64

2024-08-05 14:30 UTC, chughts requested changes

2024-08-05 14:30 UTC, chughts commented on MQTicketService/Dockerfile
> +#
copyright date needs to be modified to `# © Copyright 2019, 2024 IBM Corporation`

2024-08-05 14:30 UTC, chughts commented on MQTicketService/Dockerfile
> +# Specify base image and platform for the build
default build base

2024-08-05 14:30 UTC, chughts commented on MQTicketService/Dockerfile
> +ARG imageName=icr.io/ibm-messaging/mq:latest
Both are base images, should rename the ARGs so that it is more meaningful. eg. baseImageStep1, and baseImageStep2

2024-08-05 14:30 UTC, chughts commented on MQTicketService/Dockerfile
> +ARG imageName=icr.io/ibm-messaging/mq:latest
or baseImageBuildStage, baseImageRunStage

2024-08-05 14:30 UTC, chughts commented on MQTicketService/Dockerfile
> +# Tested with
This isn't true anymore. I think its now 9.4.0.0 only.

2024-08-05 14:30 UTC, chughts commented on MQTicketService/Dockerfile
> +    curl -Lo OpenJDK11U-jre_x64_linux_hotspot_11.0.13_8.tar.gz https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jre_x64_linux_hotspot_11.0.13_8.tar.gz && \
paramatize `jre_x64_linux_hotspot_11.0.13_8` and `11.0.13_8` so they aren't repeated, and only set once.

2024-08-05 14:30 UTC, chughts commented on MQTicketService/Dockerfile
> +    curl -Lo OpenJDK11U-jre_x64_linux_hotspot_11.0.13_8.tar.gz https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jre_x64_linux_hotspot_11.0.13_8.tar.gz && \
rather like the arm64 version

2024-08-05 14:30 UTC, chughts commented on MQTicketService/Dockerfile
> +
Remove extra lines at the end of the file

2024-08-05 14:30 UTC, chughts commented on MQTicketService/startApp.sh
> +
Update copyright to `Copyright 2019, 2024 IBM Corporation`

2024-08-06 11:34 UTC, chughts approved these changes

2024-08-06 11:38 UTC, chughts requested changes
The readme needs to be updated to show how to pass in the images (and in the case of ARM64, how to create an image), used by the docker file.

2024-08-06 11:55 UTC, rcoppen requested changes
@shreeya1510 looks good, some minor changes in review comments.

2024-08-06 11:55 UTC, rcoppen commented on MQTicketService/Dockerfile
> +ARG baseImageBuildStage=docker.io/library/maven:3.6-openjdk-11
Can this be pre-canned for arm64 builds to save the user the effort of going and working out what is needed. We do this for amd64 already.

2024-08-06 11:55 UTC, rcoppen commented on MQTicketService/Dockerfile
>  RUN if [ "$platformArch" == "amd64" ]; then \
`platformArch` is overloaded as both an ARG and an ENV, can they be individually named? e.g., `argPlatformArch` and `envPlatformArch`

2024-08-06 11:55 UTC, rcoppen commented on MQTicketService/Dockerfile
> +ARG baseImageRunStage=icr.io/ibm-messaging/mq:latest
User needs to know to specify this if they want to build on arm64 based on the MQ image they built. Is this included in a README?

2024-08-06 11:55 UTC, rcoppen commented on MQTicketService/Dockerfile
>  RUN if [ "$platformArch" == "arm64" ]; then \
The two if statements deal with amd64 and arm64, but it's not clear what should happen if the value is set to something else e.g., 'typo64'. Ideally we should check for that and fail. One option would be to pre-check and make sure the two `if` branches are safe or add an if, elif and else.

2024-08-07 10:27 UTC, rcoppen approved these changes

2024-08-07 10:35 UTC, chughts requested changes
Not sure about the exit in the platform else clause, as it won't abort the build. A good series of visible error messages may be all that is needed.

2024-08-07 10:35 UTC, chughts commented on MQTicketService/startApp.sh
> +    exit 1
Was this tested to see what happens if neither `amd64` or `arm64` have been set.

We are running a command inside a docker build. The run will exit, but not the docker build

2024-08-07 11:00 UTC, chughts approved these changes

2024-08-07 11:00 UTC, merged